development:
  host: localhost
  database: simple_tasking_development

test:
  host: localhost
  database: simple_tasking_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
